---
title: "arlequin_mantel"
author: "Alexander Lopez"
date: "8/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggpubr)
library(dplyr)

rory_theme <- theme_classic(base_size = 18) + 
  theme(axis.title.y=element_text(vjust=1.5), axis.title.x=element_text(vjust=0.2)) + #adjust axis title position
  theme(plot.margin = unit(c(.3,.3,.6,.6), "cm"), line = element_line(size = 1.25)) + #adjust plot margins and line element size
  theme(axis.line.x = element_line(colour = "black"), axis.line.y = element_line(colour = "black")) + #draw x and y axes
  theme(axis.text.x = element_text(margin=unit(c(0.5,0.5,0.5,0.5), "cm")), axis.text.y = element_text(margin=unit(c(0.5,0.5,0.5,0.5), "cm"))) + #put margins around axis labels so that nothing overlaps
  theme(axis.ticks.length =unit(-0.3, "cm")) + # move tickmarks inside the axes
  theme(panel.spacing = unit(2, units = "lines")) + #spread out facets
  theme(strip.background = element_blank()) #remove border from facet labels
```

## **Merced IBD - Pairwise Genetic Vs. Geographic Distances**
```{r}
# Read in data
merced_ibd <- read.csv("C:/Users/Alexander Lopez/Documents/Lab/waterhemp_project/data/stacks/arlequin/mantel_ibd_merced.csv", header = TRUE)
```

```{r, fig.width=8, fig.height=6}
# Plot pairwise genetic vs. geographic distances to visualize IBD
ggplot(data = merced_ibd, mapping = aes(x=Geo, y=Fst)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, formula = y~0+x) + 
  labs(x = "Kilometers") +
  ylab(expression(F["ST"]/(1-F["ST"]))) +
  stat_regline_equation(label.y = 0.225, aes(label = ..eq.label..)) +
  stat_regline_equation(label.y = 0.2, aes(label = ..rr.label..)) +
  ggtitle("Pairwise Genetic Vs. Geographic Distance", subtitle = "Merced") + 
  scale_y_continuous(breaks = seq(0, 0.25, by = 0.05), limits = c(0, 0.25)) +
  rory_theme
```

***

## **Midwest IBD - Pairwise Genetic Vs. Geographic Distances**

```{r}
# Read in Midwest data
midwest_ibd <- read.csv("C:/Users/Alexander Lopez/Documents/Lab/waterhemp_project/data/stacks/arlequin/mantel_ibd_midwest.csv", header = TRUE)
```

```{r, fig.width=8, fig.height=6}
# Plot pairwise genetic vs. geographic distances to visualize IBD
midwest_ibd$ln_km <- log(midwest_ibd$Geo) # create new column computing the natural logarithm (ln) of geo distance

midwest_ibd <- midwest_ibd %>% mutate(ln_km = ifelse(ln_km < 0, 0, ln_km)) # convert -inf values to 0

# Pairwise Genetic vs Geographic distance plot: Midwest
ggplot(data = midwest_ibd, mapping = aes(x=ln_km, y=Fst)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, formula = y~0+x) + 
  labs(x = "Ln(Kilometers)") +
  ylab(expression(F["ST"]/(1-F["ST"]))) +
  stat_regline_equation(label.y = 0.225, aes(label = ..eq.label..)) +
  stat_regline_equation(label.y = 0.2, aes(label = ..rr.label..)) +
  ggtitle("Pairwise Genetic Vs. Geographic Distance", subtitle = "Midwest") +
  scale_x_continuous(breaks = seq(0, 7, by = 1)) +
  scale_y_continuous(breaks = seq(0, 0.3, by = 0.05), limits = c(0, 0.25)) +
  rory_theme
```

***

# **AMOVA Pie Charts - Arlequin 3.5.0**

### **AMOVA - STRUCTURE Genetic Subunits**
```{r}
amova1 <- data.frame("Variation_Source" = c("AG", "APWG", "AIWP", "WI"), "SS" = c(182.667, 167.754, 919.614, 866.000), "Variance_Components" = c(0.43662, 0.21403, 0.23642, 3.04716), "Percentage_Variation" = c(11.10, 5.44, 6.01, 77.45))

ggplot(amova1, aes(x = "", y = Percentage_Variation, fill = Variation_Source)) +
  geom_col() +
  coord_polar(theta = "y") +
  rory_theme

ggplot(amova1, aes(x = "", y = Percentage_Variation, fill = Variation_Source)) +
  geom_col() +
  coord_polar("y", start = 0) +
  theme_void()

ggplot(amova1, aes(x = "", y = Percentage_Variation, fill = Variation_Source)) +
  geom_col(width=1, color="black") +
  coord_polar("y", start = 0) +
  theme_void(base_size = 18) +
  scale_fill_manual(values = c("#AED6F1", "#85C1E9", "#5DADE2", "#3498DB")) +
  labs(fill = "Variation Source", title = "Percentages of Molecular Variance")
  
  

####
amova1b <- amova1 %>% 
  arrange(desc(Variation_Source)) %>%
  mutate(prop = Percentage_Variation / sum(amova1$Percentage_Variation) *100) %>%
  mutate(ypos = cumsum(prop)- 0.5*prop )

ggplot(amova1b, aes(x = "", y = Percentage_Variation, fill = Variation_Source)) +
  geom_col(width=1, color="black") +
  coord_polar("y", start = 0) +
  theme_void(base_size = 18) +
  geom_text(aes(y = ypos, label = prop), color = "black", size=6) +
  scale_fill_brewer(palette="Blues") + 
  labs(fill = "Variation Source", title = "AMOVA Pie Chart")
```


### **AMOVA - Midwest vs Merced**

### **AMOVA - Merced**
```{r}
amova2 <- data.frame("Variation_Source" = c("APWG", "AIWP", "WI"), "SS" = c(342.049, 2406.769, 2251.500), "Variance_Components" = c(0.96074, 0.96766, 15.66370), "Percentage_Variation" = c(5.46, 5.50, 89.04))

ggplot(amova2, aes(x = "", y = Percentage_Variation, fill = Variation_Source)) +
  geom_col(width=1, color="black") +
  coord_polar("y", start = 0) +
  theme_void(base_size = 18) +
  scale_fill_manual(values = c("#85C1E9", "#5DADE2", "#3498DB")) +
  labs(fill = "Variation Source", title = "Percentages of Molecular Variance")


ggplot(amova2, aes(x = "", y = Percentage_Variation, fill = Variation_Source)) +
  geom_col(width=1, color="black") +
  coord_polar("y", start = 0) +
  theme_void(base_size = 18) +
  scale_fill_manual(values = c("#85C1E9", "#5DADE2", "#3498DB")) +
  labs(fill = "Variation Source", title = "Percentages of Molecular Variance", subtitle = "Merced")

###
amova2b <- amova2 %>% 
  arrange(desc(Variation_Source)) %>%
  mutate(prop = Percentage_Variation / sum(amova2$Percentage_Variation) *100) %>%
  mutate(ypos = cumsum(prop)- 0.5*prop)

ggplot(amova2b, aes(x = "", y = Percentage_Variation, fill = Variation_Source)) +
  geom_col(width=1, color="black") +
  coord_polar("y", start = 0) +
  theme_void(base_size = 18) +
  geom_text(aes(y = ypos, label = prop), color = "black", size=6) +
  scale_fill_manual(values = c("#85C1E9", "#5DADE2", "#3498DB")) +
  labs(fill = "Variation Source", title = "AMOVA Pie Chart", subtitle = "Merced")
```

### **AMOVA - Midwest**


